### ISSUE TITLE
Bot stop (TypeError: 'dict_keys' object is not subscriptable)

### ISSUE THREAD

**Issue by Archerman888** [AdriaGual/marvel-snap-bot#11]
![image](https://user-images.githubusercontent.com/83743669/213413060-85bd1013-1073-4931-8f11-70e7c956918c.png)
Bot stop on turn 5

![image](https://user-images.githubusercontent.com/83743669/213414274-64324430-0407-4969-bc92-07c46608238e.png)

**Comment by AdriaGual** [comment]
Fixed in the last commit https://github.com/AdriaGual/marvel-snap-bot/commit/9ff79f6cd10ea4953c15f430b14a919272a1bad1
