### ISSUE TITLE
New error?

### ISSUE THREAD

**Issue by azrulshah** [AdriaGual/marvel-snap-bot#12]
Connection result: already connected to 127.0.0.1:5555

adb.exe: device offline
error: device offline
Traceback (most recent call last):
  File "C:\Users\Azrul\marvel-snap-bot\start.py", line 22, in <module>
    screenshot_dimensions = screenshot.shape
                            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by AdriaGual** [comment]
It says that it can't connect to your adb, check that you have Bluestacks correctly initiated and that `adb devices` returns your emulator.
