### ISSUE TITLE
Missing 0.png

### ISSUE THREAD

**Issue by modonnell3573** [AdriaGual/marvel-snap-bot#14]
Output:

```
Connection result: connected to XXX.0.0.1:5555
[ WARN:0@0.129] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) 
findDecoder imread_('/mnt/c/Users/Matt/Desktop/Games/mods/marvelSnap/marvel-snap-bot-master/tmp/0.png'): 
can't open/read file: check file path/integrity             
Traceback (most recent call last):
File "start.py", line 25, in <module>
screenshot_dimensions = screenshot.shape
AttributeError: 'NoneType' object has no attribute 'shape'                                                              
```

python version is 3.8.10

tmp folder exists at that location but there is no 0.png. 

Am I supposed to populate one? I didn't see anything about this in the readme

**Comment by AdriaGual** [comment]
Check your config.py file.

**Comment by modonnell3573** [comment]
anything more specific? I think I filled out all the fields from the README

**Comment by AdriaGual** [comment]
Maybe your path isn't correctly setup.

`/mnt/c/Users/Matt/Desktop/Games/mods/marvelSnap/marvel-snap-bot-master/tmp/0.png'`

Check the "/mnt/c/Users" route

**Comment by modonnell3573** [comment]
`pwd` in the install gives

`/mnt/c/Users/Matt/Desktop/Games/mods/marvelSnap/marvel-snap-bot-master `

and `ls` gives
```
README.md     config.py   data            fields.py             images   mana.py              print_turn.py     tmp
__pycache__   cp_calc.py  field_cards.py  hand_cards.py         info.py  print_fields.py      requirements.txt  turn.py
clear_tmp.py  cp_list.py  field_list.py   hand_cards_number.py  log.txt  print_hand_cards.py  start.py          utils     
```

**Comment by modonnell3573** [comment]
I'm currently running it in Windows Subsystem for Linux . I had to change a bunch of the "\\"s to "/" . I'm trying again in powershell

**Comment by human-tetris** [comment]
try to screenshot start screen of marvel snap in .png and put it as 'marvel-snap-bot-master/tmp/0.png'
it worked for me

**Comment by modonnell3573** [comment]
It worked no problem in powershell. No changes other than that. Not sure what is causing it but still reproducible

**Comment by AdriaGual** [comment]
On the config file, replace the "/" for "\\".

Paths have to be in this format:
`project_path = 'F:\\WebPages\\Bots\\marvelSnapBot'`
