### ISSUE TITLE
Can't get it to start?

### ISSUE THREAD

**Issue by paperc07** [AdriaGual/marvel-snap-bot#17]
Git Bash
$ START.PY
bash: START.PY: command not found

then if I try CMD I get this one

C:\Users\paper\marvel-snap-bot>start.py
Traceback (most recent call last):
  File "C:\Users\paper\marvel-snap-bot\start.py", line 1, in <module>
    from utils import android_connection, global_utils
  File "C:\Users\paper\marvel-snap-bot\utils\android_connection.py", line 4, in <module>
    import config
  File "C:\Users\paper\marvel-snap-bot\config.py", line 1
    adb_path = 'C:\Users\paper\Desktop\platform-tools'
                                                      ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

Then if I open windows powershell 

in the marvel-snap-bot folder it just like seems like it opened a window but it disappears

**Comment by AdriaGual** [comment]
Check your config file and follow exactly the format of the path.
Example here:
adb_path = 'D:\\JocsPC\\Nox\\bin'

It's with \\ instead of \

Also make sure you can adb (just execute `adb devices`) on the path you put.

**Comment by paperc07** [comment]
so I can't have it like this? 

'C:\Users\paper\marvel-snap-bot\platform-tools\adb.exe'

**Comment by AdriaGual** [comment]
![image](https://user-images.githubusercontent.com/25803231/215267333-8459bb0e-0046-478f-a414-a6abe15e81d4.png)

**Comment by paperc07** [comment]
ok fixed it now im getting this

$ python start.py
Traceback (most recent call last):
  File "C:\Users\paper\marvel-snap-bot\start.py", line 1, in <module>
    from utils import android_connection, global_utils
  File "C:\Users\paper\marvel-snap-bot\utils\android_connection.py", line 4, in <module>
    import config
  File "C:\Users\paper\marvel-snap-bot\config.py", line 1
    adb_path = 'C:\Users\paper\marvel-snap-bot\platform-tools\'
               ^
SyntaxError: unterminated string literal (detected at line 1)

**Comment by paperc07** [comment]
I solved the syntax error by doing this

adb_path = r"C:\Users\paper\marvel-snap-bot\platform-tools"
project_path = r'C:\Users\paper\marvel-snap-bot'

**Comment by paperc07** [comment]
Ok I think I solved ModuleNotFoundError: No module named 'cv2' by putting this inside gitbash

pip install opencv-contrib-python

**Comment by paperc07** [comment]
OMG ITS WORKING!!!! Will report back next sorry for all this spam just wanted to leave this if others need help they might be able to reference this I will move it to closed though

**Comment by Ourclouds** [comment]
Any clue has to how you got the 'No module names 'cv2' to work?

I tried doing pip install opencv-contrib-python

but all I get is this;

Requirement already satisfied: opencv-contrib-python in c:\users\thesc\appdata\local\programs\python\python311\lib\site-packages (4.7.0.68)
Requirement already satisfied: numpy>=1.21.2 in c:\users\thesc\appdata\local\programs\python\python311\lib\site-packages (from opencv-contrib-python) (1.24.1)

so no idea what to do next.

**Comment by paperc07** [comment]
No I don't honestly it worked for me after that. But what errors or messages are you getting now? or is just not opening?

**Comment by paperc07** [comment]
@Ourclouds you ever figure it out I know what to do now just now seeing this thread again
