### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ghysnzsy** [AdriaGual/marvel-snap-bot#19]
Traceback (most recent call last):
  File "C:\Users\DiC\marvel-snap-bot\start.py", line 15, in <module>
    android_connection.connect()
  File "C:\Users\DiC\marvel-snap-bot\utils\android_connection.py", line 10, in connect
    connect_result = os.popen("adb connect 127.0.0.1:5555").read()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xeb in position 34: illegal multibyte sequence

how can i do?

and my bluestack's adb port is 64188.
so, how to change port number ?

**Comment by ghysnzsy** [comment]
i find in android_connection.py and global_utils.py

**Comment by paperc07** [comment]
What was problem just in case others have problem?
