### ISSUE TITLE
What Kazoo Deck is everyone using?

### ISSUE THREAD

**Issue by paperc07** [AdriaGual/marvel-snap-bot#21]
I deleted mine a long time ago and I am looking at the data folder in the bot and I can't determine what zoo deck to make?

antman
angela
bishop
blue marvel
Captain America
Iceman 
Kazzar
Korg
Nightcrawler
Okoye
Rocket Racoon
Spectrum

**Comment by AdriaGual** [comment]
![image](https://user-images.githubusercontent.com/25803231/215319535-6054c403-4430-483f-a538-de0a1d4c2546.png)

This is the deck I used, but make sure to use the original cards, variants are not detected (you could configure it).
