### ISSUE TITLE
Is this what the bot is supposed to be doing?

### ISSUE THREAD

**Issue by paperc07** [AdriaGual/marvel-snap-bot#22]
I let it run for a game and it wouldn't end turn but I think once.

https://youtu.be/CYC21l15UnE

**Comment by iAmMrNegative** [comment]
thats how ive been using the bot im not entirely sure if its smart enough to detect the deck and try to outplay the opponent. or if its smart enough to look at your hand an play any cards that are possible to play. i just afk and get boosters for cards LUL

**Comment by paperc07** [comment]
ok yeah if thats how its supposed to run just to farm boosters fuck it ill take it, I just wasn't sure cause he had said something about getting wins here and there and I just don't see it yet. I only got my win in my link cause they forfeited lol

**Comment by AdriaGual** [comment]
@paperc07 In the video I see you using some variant cards like kazaar, angela, captain america.
The bot hasn't been configured to detect those variant cards, if the bot can't recognise the cards, it won't apply any logic xD 
You can configure them.

**Comment by paperc07** [comment]
oh ok it was in the data folder so I thought we could use those cards, so let me go back and look at what actual cards have been configured, that's my bad.

**Comment by AdriaGual** [comment]
No problem!
