### ISSUE TITLE
Auto retreat

### ISSUE THREAD

**Issue by Wibbles790** [AdriaGual/marvel-snap-bot#24]
Hey, would it be possible to get the bot to auto retreat on turn 4? Would significantly speed up farming. I'm trying to make the changes myself but my Python is pretty terrible 😄

**Comment by paperc07** [comment]
They gotta be able too, I mean if it can end turn and hit collect rewards at the end im sure they can make it to hit retreat. But we shall see

**Comment by AdriaGual** [comment]
Yeah, we can make an option to auto retreat when turn 4 is detected but, may I ask what do we get doing that? We would be constantly losing cubes and missions that require to play cost 5 and cost 6 cards could never be done.

**Comment by Wibbles790** [comment]
If you don't care about cubes it's by far the fastest way to gain season pass levels

**Comment by AdriaGual** [comment]
Oh, for season pass, okok, I see now.

NOTED!

When I have some time spare time, will implement it. Will have to think if it'll be another script as a variant of `start.py` or start adding params to the `start.py`.

**Comment by Wibbles790** [comment]
Awesome, thank you 😄

**Comment by AdriaGual** [comment]
@Wibbles790 I have stated your idea on the 'Discussions' tab https://github.com/AdriaGual/marvel-snap-bot/discussions/31, will close this issue, but if you wanna point something else, feel free to say it on the discussion!
