### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by Archerman888** [AdriaGual/marvel-snap-bot#27]
![image](https://user-images.githubusercontent.com/83743669/215710217-3a4b869c-b97e-409e-95ac-a3afb95faba6.png)

**Comment by Wibbles790** [comment]
Try this:
pip install opencv-contrib-python

**Comment by AdriaGual** [comment]
@Archerman888 Have you reinstalled the requirements? 
`pip install -r requirements.txt`

**Comment by Archerman888** [comment]
> @Archerman888 Have you reinstalled the requirements? 
> `pip install -r requirements.txt`
Yes already reinstalled

**Comment by human-tetris** [comment]
got a similair error
![image](https://user-images.githubusercontent.com/57364666/215721959-8388f2c6-eaea-4398-8e0a-8a2fd71d4f75.png)

**Comment by human-tetris** [comment]
Rebuild the library by typing
`pip uninstall opencv-python`

then
`pip install opencv-python`

worked for me.

**Comment by Archerman888** [comment]
> Rebuild the library by typing `pip uninstall opencv-python` then `pip install opencv-python`
> 
> worked for me.

Work for me too, Thank you.
