### ISSUE TITLE
To facilitate maintenance, I made this if you need it there 

### ISSUE THREAD

**Issue by war4den** [AdriaGual/marvel-snap-bot#3]
To facilitate maintenance, I made this if you need it there 
![Snipaste_2023-01-12_11-14-44](https://user-images.githubusercontent.com/20964688/211967654-92e76c7f-e323-4aa4-9891-57e40fc19b48.jpg)

cp_list.py:
import os
def txtdict(filepath):
    dict_temp = {}
    file = open(filepath,'r')
    for line in file.readlines():
        line = line.strip()
        k = line.split(' ')[0]
        v = int(line.split(' ')[1])
        dict_temp[k] = v
    file.close()
    return dict_temp

dirPath = "D:\marvel-snap-bot-master\data\cp_list" 
files = os.listdir(dirPath)
cps={}
for file in files:
    if file.endswith(".txt"):
        with open("D:\\marvel-snap-bot-master\\data\\cp_list\\" + file, "r", encoding='utf-8') as file:
            content = file.read()+"\n"
            dirname, filename = os.path.split(file.name)
            data=txtdict(file.name)
            filename=filename[:-4]
            cps[filename]=data
            file.close()

fields can do it too

**Comment by war4den** [comment]
[cp_list.zip](https://github.com/AdriaGual/marvel-snap-bot/files/10397881/cp_list.zip)

**Comment by AdriaGual** [comment]
@war4den That's a great idea, if you want, you can do a PR to integrate it on the main branch!

Thanks!

**Comment by AdriaGual** [comment]
Closing the issue, this can be moved to a PR.
