### ISSUE TITLE
i have this error when execute start.py

### ISSUE THREAD

**Issue by pusheenp0wer** [AdriaGual/marvel-snap-bot#32]
The system cannot find the path specified.
[ WARN:0@7.371] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\aves\marvel-snap-bot\tmp\0.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\aves\marvel-snap-bot\start.py", line 22, in <module>
    screenshot_dimensions = screenshot.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by AdriaGual** [comment]
Some people found that creating the tmp folder manually fixes the issue.

**Comment by human-tetris** [comment]
also try to add 0.png screenshot of marvel snap' menu

**Comment by pusheenp0wer** [comment]
thanks that works

**Comment by AdriaGual** [comment]
I have added the files to the repo, thanks to both of you! @pusheenp0wer @human-tetris
