### ISSUE TITLE
Match does not start since new patch

### ISSUE THREAD

**Issue by human-tetris** [AdriaGual/marvel-snap-bot#33]
Bot stuck on '[get_turn] Time elapsed' status. Is this a known issue?

**Comment by AdriaGual** [comment]
Didn't know this issue, is there a way to reproduce it?

**Comment by human-tetris** [comment]
just launched the game as I used to on Bluestacks, after that launched the bot and nothing happend besides [get_turn] Time elapsed permanent loop

maybe new menu caused something?

**Comment by AdriaGual** [comment]
Have you reinstalled the requirements?

**Comment by human-tetris** [comment]
![image](https://user-images.githubusercontent.com/57364666/215898324-f51e0aa5-6322-4b17-b526-e7c13ef3deec.png)

**Comment by human-tetris** [comment]
yup, bot worked today

**Comment by AdriaGual** [comment]
For the image what I can see is that the bot is not detecting the PLAY image.

Ok, here's a list of things I would try:

- Make sure that the resolution of the emulator is 1600x900 by chosing another resolution and then going back to the 1600x900.
- Pull the new code
- Reinstall requirements
- Make sure you have this packages installed (`pip freeze`):
numpy==1.21.0
opencv_python_headless==4.6.0.66
Pillow==9.3.0
PyAutoGUI==0.9.53
rembg==2.0.30

**Comment by human-tetris** [comment]
![play_button](https://user-images.githubusercontent.com/57364666/215900929-3c59536c-74b6-4a5e-94a3-cb43e53ad7d3.png)
update of marvel-snap-bot\images\play_button.png fixed it

**Comment by human-tetris** [comment]
@AdriaGual 

![next_button](https://user-images.githubusercontent.com/57364666/215901896-04215c44-a85a-48b2-9d5c-c96e4cec8387.PNG)
next_button.png needs an update too

**Comment by AdriaGual** [comment]
My bad, didn't know about this marvel snap update, just updated the new images from PLAY and NEXT, pull the code and thanks!
