### ISSUE TITLE
thank you for your help / After today's update, the start button and next button need to be modified.

### ISSUE THREAD

**Issue by blamang** [AdriaGual/marvel-snap-bot#35]
It's a simple problem that can be solved by simply replacing the picture in the images folder. So far I have been using the program very well. thank you.

P. S. How do I make a program that immediately escapes after playing the 4th turn? If you have that Can I use?

**Comment by Niassamond** [comment]
why escaping on 4th turn ? why is that the best way?

**Comment by blamang** [comment]
Because it's a 3x faster way to earn season pass experience.

**Comment by zachleboeuf** [comment]
How is it 3x faster?

**Comment by AdriaGual** [comment]
Yesterday I uploaded the new cards from PLAY and NEXT buttons, make a pull and the bot will work as always!
But it's great that you noticed it!
COMMIT https://github.com/AdriaGual/marvel-snap-bot/commit/b6fb7e09467bc16506ef820c11f3781e96f82387

**Comment by AdriaGual** [comment]
Answering your question, the option of forfeiting on the 4rth turn hasn't been implemented yet.

Will do it when I have some spare time haha

**Comment by zachleboeuf** [comment]
I sent you an email with a couple of questions about the bot. Figured it was better than flooding the issue section.

**Comment by AdriaGual** [comment]
You can use the Discussion tab for questions so other people can also see it 🕵
