### ISSUE TITLE
1/31/23 UPDATE (Play_Button)

### ISSUE THREAD

**Issue by iAmMrNegative** [AdriaGual/marvel-snap-bot#37]
after the January 31st update the bot is having troubles with selecting the play option. to fix this simply go to the home screen where you can see the "PLAY" option then go into your files and run the "print_hand_cards.py" once that opens take a screenshot of the "PLAY" button. try to only capture the letters and not to much of the background. rename that screenshot to "play_button.PNG" and save it to the \images folder and then into the \turns folder. if you get an error from the bot after running it try and make your image smaller.

- Negative

**Comment by AdriaGual** [comment]
Yesterday I uploaded the new cards from PLAY and NEXT buttons, make a pull and the bot will work as always!
But it's great that you noticed it!
COMMIT https://github.com/AdriaGual/marvel-snap-bot/commit/b6fb7e09467bc16506ef820c11f3781e96f82387
