### ISSUE TITLE
Running without 8 images of each card?

### ISSUE THREAD

**Issue by zachleboeuf** [AdriaGual/marvel-snap-bot#39]
I had written a script for auto-passing the turns and entering games to use Agatha to farm for the season pass. Agatha has no logic that I can tell. She will play a random card from your hand to a random available location. This is fine with me I don't care if she wins. I would like for her to win a single location and that is all really. Unfortunately, Agatha steals all of the boosters. So, she currently has 18k. I was interested in using your bot so that I could farm boosters for my other cards. The process of getting 8 images for each card when I want to farm boosters for a new deck is extremely tedious. If I am not interested in the bot using any applied logic is there a way to have the bot just play random cards without needing to acquire all of those images?

I also sent this in an email. So, whichever is easier for you to reply to.

**Comment by AdriaGual** [comment]
My mail is usually full af so I spend fridays or saturdays answering the mail haha

So it's easier here (for questions you can use the Discussions tab, there, more people can answer also)

Answering you, we can do what you say, if you go to the `hand_cards.py` file, there's a method called `play_cards.py` and, if a lot of conditions happen, the bot plays random cards to every possible field, you can just remove this conditions and make the bot always play random cards!
![image](https://user-images.githubusercontent.com/25803231/215981822-199540d3-4d46-472f-9464-2c014e2acd36.png)

**Comment by zachleboeuf** [comment]
I swear I am not blind but when I went to ask a question I didn't see the discussions tab. My bad. 

Do I just comment out/remove lines 93 to 107?

**Comment by zachleboeuf** [comment]
Wait. I think I understand the code a little more now, and maybe that bright red box helps. Just remove lines 106 and 107?

**Comment by AdriaGual** [comment]
The lines 106 and 107 and the ones that will play a random card, but you can just use the play_random_cards()

Would be something like:

```
def play_cards(play_info, last_move):
    play_random_cards()
    return last_move
```

**Comment by zachleboeuf** [comment]
Do I not need
`    else:
        global_utils.click([755, 1487])`

before 
`return last_move`

**Comment by AdriaGual** [comment]
This click is to pass the turn, I wouldn't put it to be honest, may pass turns without playing cards, but you can try and see! (you can later put your conclusions on a Discussions thread or create a PR!)

**Comment by zachleboeuf** [comment]
Without it is it going to wait for the timer to time out on each turn instead of passing the turn?

**Comment by zachleboeuf** [comment]
Bluestacks is crashing when I try and launch it on my main PC. So, I can't test it at this moment.

**Comment by AdriaGual** [comment]
> Without it is it going to wait for the timer to time out on each turn instead of passing the turn?

Basically yes.
