### ISSUE TITLE
pyautogui

### ISSUE THREAD

**Issue by azrulshah** [AdriaGual/marvel-snap-bot#41]
cant play

> Traceback (most recent call last):
>   File "C:\Users\Azrul\marvel-snap-bot\start.py", line 3, in <module>
>     import info
>   File "C:\Users\Azrul\marvel-snap-bot\info.py", line 4, in <module>
>     import hand_cards
>   File "C:\Users\Azrul\marvel-snap-bot\hand_cards.py", line 9, in <module>
>     import pyautogui
> ModuleNotFoundError: No module named 'pyautogui'

already install pyautogui

> Collecting numpy==1.21.0
>   Using cached numpy-1.21.0.zip (10.3 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting opencv_python_headless==4.6.0.66
>   Using cached opencv_python_headless-4.6.0.66-cp36-abi3-win_amd64.whl (35.5 MB)
> Collecting Pillow==9.3.0
>   Using cached Pillow-9.3.0-cp311-cp311-win_amd64.whl (2.5 MB)
> Collecting PyAutoGUI==0.9.53
>   Using cached PyAutoGUI-0.9.53.tar.gz (59 kB)
>   Preparing metadata (setup.py) ... done
> ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11
> ERROR: Could not find a version that satisfies the requirement rembg==2.0.30 (from versions: none)
> ERROR: No matching distribution found for rembg==2.0.30

**Comment by AdriaGual** [comment]
Which python version do you have? I recommend using the 3.8.

**Comment by azrulshah** [comment]
3.11.1 how to change?

**Comment by AdriaGual** [comment]
You can uninstall python 3.11 and install the 3.8 version.

You can also create a virtualenv with a python 3.8 (https://github.com/pyenv/pyenv-virtualenv)

**Comment by azrulshah** [comment]
i think i can play now when i did this 

> pip install pyautogui

but the bot not playing, is the version where the bot only going to get the booster? i need bot that can boost my level (if can)

**Comment by AdriaGual** [comment]
The bot can play but you need to have the cards configured.

Check previous issues where people asked this.
https://github.com/AdriaGual/marvel-snap-bot/issues/21
https://github.com/AdriaGual/marvel-snap-bot/issues/4
https://github.com/AdriaGual/marvel-snap-bot/issues/1

**Comment by paperc07** [comment]
We have to install the auto gui? I see it in the marvel-snap-bot folder but wasn't aware we had to install it

**Comment by AdriaGual** [comment]
You have to install all the requirements listed in the requirements.txt, i use pyautogui because it has a built in "locateOnScreen" which is a template matching that works a bit better than the one I coded so, why not use it, right?
