### ISSUE TITLE
Turn 7 

### ISSUE THREAD

**Issue by human-tetris** [AdriaGual/marvel-snap-bot#49]
Sometimes you have Magik or a special field which provides turn 7. Can you add it in order to bot function properly?

![6-7](https://user-images.githubusercontent.com/57364666/216281025-36e23443-a737-443e-bb7d-ed3aaef98229.png)

**Comment by human-tetris** [comment]
![6](https://user-images.githubusercontent.com/57364666/216315874-19d56bc1-fe0b-493a-ac18-66beb17e27e6.png)

**Comment by AdriaGual** [comment]
True! Added it on the last commit https://github.com/AdriaGual/marvel-snap-bot/commit/346556bfddd62595b6947984d20326be0852b0f6

**Comment by human-tetris** [comment]
nice, ty!
