### ISSUE TITLE
Dependency Conflict rembq and numpy

### ISSUE THREAD

**Issue by zachleboeuf** [AdriaGual/marvel-snap-bot#54]
ERROR: Cannot install -r requirements.txt (line 2), numpy==1.21.0 and rembg==2.0.30 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.21.0
    opencv-python-headless 4.6.0.66 depends on numpy>=1.19.3; python_version >= "3.9"
    opencv-python-headless 4.6.0.66 depends on numpy>=1.14.5; python_version >= "3.7"
    opencv-python-headless 4.6.0.66 depends on numpy>=1.17.3; python_version >= "3.8"
    rembg 2.0.30 depends on numpy~=1.23.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by AdriaGual** [comment]
That's weird, but for now just install numpy 1.23.5.
Also make sure you have this opencv versions:
```
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66
```

**Comment by zachleboeuf** [comment]
Alright. I will. Do you think it might cause the error with the bot exiting after field detection?

**Comment by AdriaGual** [comment]
I don't think so... But next time it exits, check if there's any error logged.

**Comment by zachleboeuf** [comment]
I posted the log on my other issue post. I check it everytime and it just has the output of the field location and then ends. Unless the error log is somewhere besides the log file in the marvel-snap-bot folder.

**Comment by zachleboeuf** [comment]
Those opencv installs actually did fix the error with it closing on field detect.

**Comment by rahul-dev-app** [comment]
The opencv installs did not fix the issue for my. I had to install numpy 1.23.5
