### ISSUE TITLE
android_connection

### ISSUE THREAD

**Issue by seennz** [AdriaGual/marvel-snap-bot#57]
hi,

not able to find 'android_connection' within modules, am I missing something here?

**Comment by seennz** [comment]
![image](https://user-images.githubusercontent.com/123750430/216988991-14eae110-b366-4127-b91a-4e286ff3e837.png)

**Comment by human-tetris** [comment]
check port setting inside utils.py and emulator. are they the same?

**Comment by seennz** [comment]
There is nothing like "android_connection" in utils.py? And it's module related...

**Comment by AdriaGual** [comment]
Seems like it's trying to call the wrong (utils.py from python3.10, not from the repo), try installing python 3.8 and its dependencies.

Hope it helps!
