### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by cheryiit** [AdriaGual/marvel-snap-bot#6]
[ WARN:0@0.829] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\Yi─şit\marvel-snap-bot\tmp\0.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "start.py", line 22, in <module>
    screenshot_dimensions = screenshot.shape
AttributeError: 'NoneType' object has no attribute 'shape'

why i am getting the errors ?

**Comment by AdriaGual** [comment]
There are a bunch of things you can check:
- Do you have correctly installed Bluestacks? (resolution 1600x900)
- Have you changed the `config.py` with all the paths correctly setup?
- Do you have python 3.8 or 3.9? cv2 has problems with versions above 3.9.

Hope it helps

**Comment by spiderowl** [comment]
i think you need to add a folder called tmp in marvel-snap-bot folder.

**Comment by AdriaGual** [comment]
As @spiderowl said, you should follow the README.md folder structure.

**Comment by cheryiit** [comment]
yes thats correct the reason of error is the turkish alphabet
I tried to change project directory and I fixed it. But I also tried to just change the tmp folder to C:\\, it wasn't enough and i got the same error again.
