### ISSUE TITLE
ModuleNotFoundError : No module named 'cv2'

### ISSUE THREAD

**Issue by KSteez11** [AdriaGual/marvel-snap-bot#65]
Do you know why I would be getting this error by any chance and how to fix it?

**Comment by KSteez11** [comment]
<img width="297" alt="Screenshot 2023-02-08 154222" src="https://user-images.githubusercontent.com/124807247/217657756-1046d8f4-8747-457d-b48e-697add492585.png">

**Comment by AdriaGual** [comment]
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66

**Comment by W33dox** [comment]
Hey Mate :)

Thanks for the first answer, i had the same problem and it helped. 

But now i am getting this: 
![Screenshot 2023-02-09 122517](https://user-images.githubusercontent.com/124884303/217799847-dcea6566-775f-4385-bdfd-75ba566204b9.png)

Is there anything wrong with my Python installation? 
I am a total noob and i am trying to learn by doin :D 

Greetings from Germany

**Comment by W33dox** [comment]
Fixed it with this command: pip install pyautogui
