### ISSUE TITLE
Error while running python start.py

### ISSUE THREAD

**Issue by chonthach** [AdriaGual/marvel-snap-bot#66]
<img width="630" alt="Capture" src="https://user-images.githubusercontent.com/18635673/217683219-80460d4f-9a92-4488-bef2-d8d8e7a9ac59.PNG">

This is as far as I got into into trying to get it to work but I don't know where or how to fix this. looks like its duping the path. Any help will be appreciated thanks for your work.

**Comment by chonthach** [comment]
this is my config 

![image](https://user-images.githubusercontent.com/18635673/217724538-81c3c4ff-b60b-41bf-b0b2-48ecd9331af9.png)

**Comment by AdriaGual** [comment]
Seems like your are missing the `:` after the C drive.

Instead of:
adb_path = 'C\\...
project_path = 'C\\...

Put:
adb_path = 'C:\\...
project_path = 'C:\\...

**Comment by chonthach** [comment]
That worked! but another ran into another problem do i need to download and install libgtk2 and pkg-config said?
![image](https://user-images.githubusercontent.com/18635673/217757248-7b301f86-be58-442b-9ec0-23dd9270fa47.png)

**Comment by AdriaGual** [comment]
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66

**Comment by chonthach** [comment]
Thank you so much everything is working right now!
