### ISSUE TITLE
loop in get_turn

### ISSUE THREAD

**Issue by terrycwc1124** [AdriaGual/marvel-snap-bot#69]
Hello,

After I execute the start.py, the log keep prompt in "get turn". I have the game started in BlueStacks, any idea? thanks!
===================================================
02/09/2023 11:37:26 PM Connection result: already connected to 127.0.0.1:5555

02/09/2023 11:37:29 PM [get_turn] Time elapsed: 0:00:00.101567
02/09/2023 11:37:30 PM [get_turn] Time elapsed: 0:00:00.079594
02/09/2023 11:37:33 PM [get_turn] Time elapsed: 0:00:00.108149
02/09/2023 11:37:35 PM [get_turn] Time elapsed: 0:00:00.110727
02/09/2023 11:37:38 PM [get_turn] Time elapsed: 0:00:00.107244
02/09/2023 11:37:40 PM [get_turn] Time elapsed: 0:00:00.138098
02/09/2023 11:37:42 PM [get_turn] Time elapsed: 0:00:00.084114
02/09/2023 11:37:43 PM [get_turn] Time elapsed: 0:00:00.083595
02/09/2023 11:37:45 PM [get_turn] Time elapsed: 0:00:00.084926
02/09/2023 11:37:46 PM [get_turn] Time elapsed: 0:00:00.084710

**Comment by AdriaGual** [comment]
@terrycwc1124 This happens usually when the bot can't find the PLAY or the NEXT buttons.

Things you can check:

- Marvel Snap is in the version 11.18.1+1
- You have the latest code of the repo (git pull)
- The resolution of your BS is 1600x900

**Comment by azrulshah** [comment]
for me the page is at 'news' so need to click 'main' manually

**Comment by terrycwc1124** [comment]
Thanks , issue resolved!
