### ISSUE TITLE
Synthax error, i don't understand..

### ISSUE THREAD

**Issue by Zazza23** [AdriaGual/marvel-snap-bot#7]
File "C:\Users\aaa\marvel-snap-bot\config.py", line 1
    adb_path = C:\Users\aaa\AppData\Local\Android\Sdk\platform-tools
                ^
SyntaxError: invalid syntax

I can't figure out what the problem is, I tried putting the folder in other paths but nothing changed.

**Comment by Zazza23** [comment]
Thanks for the quick reply Adria. The syntax error is on ":" I'll leave you a picture for you to understand.
![718d48377e8d44c086687e9d2b8a2914](https://user-images.githubusercontent.com/122761818/212628119-e3563603-17bc-45a4-9a8f-228509b47df5.png)

**Comment by AdriaGual** [comment]
Your adb_path (and the others also), are not correct.

Just put this: `adb_path = 'C:\\Users\\zazzone23\\marvel-snap-bot\\platform-tools'`

For the other paths is the same idea using \\ instead of \ and all in single quotes.

**Comment by Zazza23** [comment]
Now works! But I have another problem it doesn't find all the cards and it doesn't find any fields. I also enabled the screenshot option but it doesn't find the cards. I don't know if it's normal that I don't skip the turn when the mana is insufficient for the cards or it's finished.
![77503aa6224ecead0f37bb7d490993e3](https://user-images.githubusercontent.com/122761818/212774449-3c231bed-8abc-44be-b2a4-a2034dd81863.png)
![6a86e856aa009a4cf8d4e71eb3c72e59](https://user-images.githubusercontent.com/122761818/212774521-902f1b0a-62ce-43e5-98f3-ba8965a48fd9.png)

**Comment by Zazza23** [comment]
Now he can't even find blue marvel when he used to at least find that.
![f60e959c26ec7c47c9525e3edd7d9c6e](https://user-images.githubusercontent.com/122761818/212774961-a98f325f-6832-4365-a602-28ea039fb15b.png)

**Comment by AdriaGual** [comment]
@Zazza23 You can take screenshots of each card and put it on the folder `./data/card_name`.

Hope it helps!

**Comment by Zazza23** [comment]
I took some screenshots but it doesn't change much.. But I'm not complaining about what it has to do. Thanks for the help
