### ISSUE TITLE
Bot gets stuck at this area

### ISSUE THREAD

**Issue by chonthach** [AdriaGual/marvel-snap-bot#73]
after the match sometimes the bot would accidently get to this page and get stuck there.
![image](https://user-images.githubusercontent.com/18635673/218226140-79171cfd-ebcf-4958-8716-1c5f9d2b8472.png)
I think the way it gets there is maybe my game is a little bit of a lag and the bot keeps pressing the finish button after a match. Some how it pressed news then patch notes to get there. maybe somehow theres a wait time after a match so it cant spam during lag.
![image](https://user-images.githubusercontent.com/18635673/218226376-a470487a-7181-4073-9f68-4cc25e66d835.png)

**Comment by AdriaGual** [comment]
Hmm you can try adding a time.sleep (add also the import) before the click in the play_cards function (hand_cards.py file)
![image](https://user-images.githubusercontent.com/25803231/218250761-53ffb4cf-32a1-40cd-9de1-c93412772f7d.png)

**Comment by chonthach** [comment]
sorry, I didnt understand your last comment. What is the import? the play_cards codes you paste? I see that code in the hand_cards.py, or u mean add the time.sleep at that area before the play_cards function.

**Comment by AdriaGual** [comment]
`import time`

And then put a sleep on the last else

**Comment by azrulshah** [comment]
> 

can u share example here?
so we can just copy and paste

**Comment by AdriaGual** [comment]
`
import time

# Make a turn play
def play_cards(play_info, last_move):
    # If we have mana to play
    if play_info['mana'] > 0:
        # Get the best possible card and the field to play
        play_to_make = cp_calc.calc_play(play_info)
        # Check if we are trying to make the same play
        if last_move[1] != play_to_make[1] and last_move[2] != play_to_make[2]:
            # If we know the card and there's a field to play
            if play_to_make[0] == 1 and len(play_info['active_fields']) > 0:
                # Play the card
                play_a_card_to_a_field(
                    play_to_make[1], play_to_make[2])
                # Save the last_move
                last_move = play_to_make
            elif play_to_make[0] == 1:
                play_a_card_to_every_field(play_to_make[1])
                play_random_cards()
            else:
                play_random_cards()
        else:
            play_a_card_to_every_field(play_to_make[1])
            play_random_cards()
    else:
        time.sleep(4)
        global_utils.click([755, 1487])
        time.sleep(4)
    return last_move`

**Comment by paperc07** [comment]
Do we all need that? Or is that code already in?

**Comment by azrulshah** [comment]
just try that Adria but still same, stuck at news

**Comment by AdriaGual** [comment]
@azrulshah This was just adding a delay because @chonthach said his emulator had lag.

**Comment by azrulshah** [comment]
i see, any ways to fix mine? to get bot to click main tab when stuck on news?

**Comment by AdriaGual** [comment]
Seems like it makes a double click, try debugging the last click function.

**Comment by chonthach** [comment]
Sorry been busy just tried to fix it thjnk it it might be delay. But it will get stuck at news

**Comment by azrulshah** [comment]
can i make a suggestion? how about each time before press 'play', press 'main' first, can it be done?

**Comment by AdriaGual** [comment]
@azrulshah That would be an easy fix i think, you can put it in discussions
