### ISSUE TITLE
Cant start because adb_path?

### ISSUE THREAD

**Issue by YohanesH** [AdriaGual/marvel-snap-bot#76]
C:\Users\towny\marvel-snap-bot>Python start.py
Traceback (most recent call last):
  File "C:\Users\towny\marvel-snap-bot\start.py", line 15, in <module>
    android_connection.connect()
  File "C:\Users\towny\marvel-snap-bot\utils\android_connection.py", line 9, in connect
    os.chdir(config.adb_path)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\towny\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe'

C:\Users\towny\marvel-snap-bot>

I donlowd it from : https://androidsdkmanager.azurewebsites.net/Platformtools
because i couldnt find the android on local so i search on google and found out that adb is located at android\\sdk\platform-tools

btw after i succses to run start.py are i need to set up other thing

**Comment by AdriaGual** [comment]
This has been answered, check the closed issues please.

Or you can open a thread on the discussions tab so other people can help.

**Comment by HolidayPhenom** [comment]
Your file location should just be the platform tools folder, not the actual "adb.exe"

**Comment by AdriaGual** [comment]
@HolidayPhenom Thanks for the explanation! 

For the double backslashes he says that the path should be:
`adb_path = 'C:\\Users\\towny\\AppData\\Local\Android\\Sdk\\platform-tools\\'`
