### ISSUE TITLE
I just tried running it since update

### ISSUE THREAD

**Issue by paperc07** [AdriaGual/marvel-snap-bot#81]
Had this error first

ile "C:\Users\paper\marvel-snap-bot\start.py", line 51, in <module>
    player_turn = turn.get_turn(screenshot, screenshot_dimensions, False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\marvel-snap-bot\turn.py", line 23, in get_turn
    searched_turn = global_utils.search(
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\marvel-snap-bot\utils\global_utils.py", line 22, in search
    result = cv2.matchTemplate(haystack_image, screenshot, method)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

2nd error

Traceback (most recent call last):
  File "C:\Users\paper\marvel-snap-bot\start.py", line 69, in <module>
    last_move = hand_cards.play_cards(play_info, last_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\marvel-snap-bot\hand_cards.py", line 95, in play_cards
    play_to_make = cp_calc.calc_play(play_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\marvel-snap-bot\cp_calc.py", line 46, in calc_play
    if cp_list.cps[hand_card[0]]['average_cp'] > max_cp_play and cp_list.cps[hand_card[0]]['mana'] <= play_info['mana']:
       ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'blue_marvel'

**Comment by paperc07** [comment]
yeah everytime I get blue marvel in my hand it  shuts it down

**Comment by paperc07** [comment]
NVM had to re git the cp_list.py and data folders.

**Comment by eimia-q** [comment]
I had the same issue with Sword Master, turns out the Data file was named sword_master and the cp_list was named swordmaster. If anyone else has similar issues, it's worth going through and checking everything is the same format.

**Comment by paperc07** [comment]
yeah I had same problem so I deleted folder and readded lol
