### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by Krwawyy** [AdriaGual/marvel-snap-bot#93]
Him im getting error as in title + "ERROR: Cannot install numpy==1.21.0 and opencv-python-headless==4.6.0.66 because these package versions have conflicting dependencies." when doing "pip install -r requirements.txt".
What I did:
- pip install opencv-contrib-python
- pip install opencv-python-headless==4.6.0.66
- pip install opencv-python==4.7.0.68
- pip install --upgrade pip setuptools wheel

**Comment by paperc07** [comment]
Go do a pip freeze and see what all you have first and then post back

**Comment by Krwawyy** [comment]
Thats what i have installed:
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
appdirs==1.4.4
async-timeout==4.0.2
asyncer==0.0.2
attrs==22.2.0
certifi==2022.12.7
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.6
coloredlogs==15.0.1
docker==6.0.1
fastapi==0.87.0
filetype==1.2.0
flatbuffers==23.1.21
frozenlist==1.3.3
h11==0.14.0
humanfriendly==10.0
idna==3.4
ImageHash==4.3.1
imageio==2.25.1
llvmlite==0.39.1
MouseInfo==0.1.3
mpmath==1.2.1
multidict==6.0.4
networkx==3.0
numba==0.56.4
numpy==1.23.5
onnxruntime==1.13.1
opencv-contrib-python==4.7.0.68
opencv-python==4.7.0.68
opencv-python-headless==4.6.0.66
packaging==23.0
Pillow==9.3.0
pooch==1.6.0
protobuf==4.22.0
PyAutoGUI==0.9.53
pydantic==1.10.5
PyGetWindow==0.0.9
PyMatting==1.1.8
PyMsgBox==1.0.9
pyperclip==1.8.2
pyreadline3==3.4.1
PyRect==0.2.0
PyScreeze==0.1.28
pytesseract==0.3.10
python-multipart==0.0.5
pytweening==1.0.4
PyWavelets==1.4.1
pywin32==305
rembg==2.0.30
requests==2.28.2
scikit-image==0.19.3
scipy==1.9.3
six==1.16.0
sniffio==1.3.0
starlette==0.21.0
sympy==1.11.1
tifffile==2023.2.3
tqdm==4.64.1
typing_extensions==4.5.0
urllib3==1.26.14
uvicorn==0.20.0
watchdog==2.1.9
websocket-client==1.5.0
yarl==1.8.2

**Comment by paperc07** [comment]
So you don't need it then you already have everything so skip that and let me know what your next error is

**Comment by Krwawyy** [comment]
$ python start.py
Traceback (most recent call last):
  File "C:\Users\xxx\marvel-snap-bot\start.py", line 1, in <module>
    from utils import android_connection, global_utils
  File "C:\Users\xxx\marvel-snap-bot\utils\global_utils.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by paperc07** [comment]
That's crazy cause you definitely have it you actually have 3. Umm what about if you get it from the website opencv

**Comment by Krwawyy** [comment]
I did install it from website aswelll

**Comment by paperc07** [comment]
ok and I guess just go ahead and do a pip uninstall and do them all manually again so 

pip uninstall opencv-contrib-python==4.7.0.68
pip uninstall opencv-python==4.7.0.68
pip uninstall opencv-python-headless==4.6.0.66

then do a reinstall 
pip install opencv-contrib-python==4.7.0.68
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66

**Comment by Krwawyy** [comment]
python start.py still not working but!
python3 start.py printing "$ python3 start.py
* daemon not running; starting now at tcp:5037
* daemon started successfully
Connection result: cannot connect to 127.0.0.1:5555: No connection could be made because the target machine actively refused it. (10061)

adb.exe: device '127.0.0.1:5555' not found
error: device '127.0.0.1:5555' not found
Traceback (most recent call last):
  File "C:\Users\xxx\marvel-snap-bot\start.py", line 23, in <module>
    screenshot_dimensions = screenshot.shape
AttributeError: 'NoneType' object has no attribute 'shape'"

**Comment by paperc07** [comment]
ok did you go get the platform tools and put it in the main folder also check this out real quick and maybe this will help I made a thread about how to install #74

**Comment by Krwawyy** [comment]
![image](https://user-images.githubusercontent.com/81049694/219900861-412767f5-70de-4908-903c-80b9787e43e4.png)
![image](https://user-images.githubusercontent.com/81049694/219900897-7a9c6198-6dd8-4b8d-98e0-df3b22e77f75.png)

**Comment by paperc07** [comment]
ok these are all related issues while I go look you can too #32 #6 #12 #14 #20

**Comment by paperc07** [comment]
ok it's not connecting to adb hold please

**Comment by Krwawyy** [comment]
adb devices returns nothing

**Comment by paperc07** [comment]
is adb turned on inside of bluestacks?

**Comment by Krwawyy** [comment]
Yup

**Comment by paperc07** [comment]
ok try in CMD adb devices and see what you get

**Comment by Krwawyy** [comment]
adb server is out of date.  killing...
* daemon started successfully *
List of devices attached

**Comment by paperc07** [comment]
and there's no devices? try adb start-server

**Comment by Krwawyy** [comment]
PS C:\Users\xxx\marvel-snap-bot> adb start-server
PS C:\Users\xxx\marvel-snap-bot> adb devices
List of devices attached

**Comment by paperc07** [comment]
ummmm

adb kill-server
adb start-server

**Comment by paperc07** [comment]
mine says this 

$ adb version
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

**Comment by Krwawyy** [comment]
PS C:\Users\xxx\marvel-snap-bot> adb start-server
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

and 

$ python3 start.py
adb server version (31) doesn't match this client (41); killing...
* daemon started successfully
Connection result: cannot connect to 127.0.0.1:5555: No connection could be made because the target machine actively refused it. (10061)

Connection result: cannot connect to 127.0.0.1:5555: No connection could be made because the target machine actively refused it. (10061)

adb.exe: device '127.0.0.1:5555' not found
error: device '127.0.0.1:5555' not found
Traceback (most recent call last):
  File "C:\Users\xxx\marvel-snap-bot\start.py", line 23, in <module>
    screenshot_dimensions = screenshot.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Krwawyy** [comment]
How can i uninstall old adb?
I've probably have installed adb somewhen

**Comment by paperc07** [comment]
turn off antivirus and windows defender and firewall and try it

**Comment by paperc07** [comment]
well just go to that website and get the new version and then just extract that platform tools to the base of your marvel snap bot folder

**Comment by paperc07** [comment]
also what about this 

1- adb kill-server

3- adb tcpip 5555

4- adb connect (your device ip):5555

**Comment by Krwawyy** [comment]
But even with platform-tools folder deleted i can adb version, so thats probably not the same adb right?

**Comment by paperc07** [comment]
probably let me see the proper way to uninstall

**Comment by Krwawyy** [comment]
![image](https://user-images.githubusercontent.com/81049694/219901488-6e19ed9c-b552-4d95-b383-4fef64aff1a8.png)
there was not android device

**Comment by paperc07** [comment]
one guy said this 

I got this error when I had Bluestacks emulator started together with my phone attached. When I typed in command prompt adb devices I could see two devices:

adb devices
List of devices attached
dfdcdc9c        device
emulator-5554   device
Before typing adb connect I had to type -s and device ID:

adb -s dfdcdc9c tcpip 5555
adb -s dfdcdc9c connect <ip addr>

**Comment by Krwawyy** [comment]
Ye but i have none in adb devices

**Comment by paperc07** [comment]
what about 

adb disconnect

**Comment by paperc07** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/9095222/219901555-e7d4c20c-4743-4930-867f-e43ebc32b807.png">

**Comment by paperc07** [comment]
did you get the new version from website yet?

**Comment by Krwawyy** [comment]
well i've deleted platform-tools folder on other hard drive

**Comment by paperc07** [comment]
ok thats fine now go get the new one from link above

**Comment by Krwawyy** [comment]
I did, still same error, adb devices returns list of 0
but version changed

**Comment by paperc07** [comment]
ok sometimes it gets struck try 

adb kill-server
adb start-server

**Comment by Krwawyy** [comment]
* daemon not running; starting now at tcp:5037
* daemon started successfully
but still no devices

**Comment by paperc07** [comment]
I wonder why its running on port 5037 also ok for the hell of it restart your pc and try again

**Comment by Krwawyy** [comment]
sure brb

**Comment by paperc07** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/9095222/219901762-77aa52fd-2049-4245-ab44-15912e467e91.png">

**Comment by Krwawyy** [comment]
PS C:\Users\xxxx\marvel-snap-bot> adb tcpip 5555
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: no devices/emulators found

no clue why

**Comment by paperc07** [comment]
yeah its not even picking up bluestacks

**Comment by paperc07** [comment]
umm you have the latest bluestacks 5?

**Comment by Krwawyy** [comment]
![image](https://user-images.githubusercontent.com/81049694/219902060-2c2cd289-7b90-4c49-97a8-44428c1ae218.png)
no clue

**Comment by Krwawyy** [comment]
i've tried connecting my phone to computer and its listing

**Comment by paperc07** [comment]
so the phone works and you see it but not bluestacks?

**Comment by Krwawyy** [comment]
![image](https://user-images.githubusercontent.com/81049694/219902112-b37b750a-2d7b-41e5-b91c-d3ca4927e5b4.png)
yes

**Comment by paperc07** [comment]
https://stackoverflow.com/questions/23104394/daemon-not-running-starting-it-now-on-port-5037

**Comment by Krwawyy** [comment]
So, ive did PS C:\Users\xxx\marvel-snap-bot> adb connect localhost:50459
connected to localhost:50459
![image](https://user-images.githubusercontent.com/81049694/219902241-4e0c5a7b-3447-4cb3-a00d-376c22566ee4.png)
and 
PS C:\Users\xxx\marvel-snap-bot> adb devices
List of devices attached
localhost:50459 device

**Comment by paperc07** [comment]
so I believe its see it now right?

**Comment by Krwawyy** [comment]
probably but still ModuleNotFoundError: No module named 'cv2'
🤣

**Comment by paperc07** [comment]
post full error please

**Comment by Krwawyy** [comment]
$ python start.py
Traceback (most recent call last):
  File "C:\Users\dawid\marvel-snap-bot\start.py", line 1, in <module>
    from utils import android_connection, global_utils
  File "C:\Users\dawid\marvel-snap-bot\utils\global_utils.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by paperc07** [comment]
ok the adb problem is solved then for now lets move on

**Comment by paperc07** [comment]
what version of python do you have?

**Comment by Krwawyy** [comment]
PS C:\Users\xxx\marvel-snap-bot> python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by paperc07** [comment]
just for bullshit purposes cause I think someone got an error before with that go get the latest python please

**Comment by Krwawyy** [comment]
nah wait i did python start.py not python3 start.py
with python3 i get
Connection result: cannot connect to 127.0.0.1:5555: No connection could be made because the target machine actively refused it. (10061)

adb.exe: device '127.0.0.1:5555' not found
error: device '127.0.0.1:5555' not found
Traceback (most recent call last):
  File "C:\Users\dawid\marvel-snap-bot\start.py", line 23, in <module>
    screenshot_dimensions = screenshot.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by paperc07** [comment]
grrrrrrr lol

**Comment by Krwawyy** [comment]
it might take a minute, i've got a lot of pythons installed apparently xD

**Comment by paperc07** [comment]
yeah it sounds like a disaster like you been using python for a while I see all those packages and was like oh man

**Comment by paperc07** [comment]
once you get it , it should say upgrade or something

**Comment by Krwawyy** [comment]
Im a it student so i've got shit ton of compilers and stuff like that, every semester there is new language, new version to download and yea

**Comment by paperc07** [comment]
ahh that makes sense so you got the new version now?

**Comment by Krwawyy** [comment]
yup but windows doesn't see it yet, "python" opens microsoft store

**Comment by paperc07** [comment]
when you click on start.py? im not sure what you mean

**Comment by Krwawyy** [comment]
works now but still same error
$ python start.py
Traceback (most recent call last):
  File "C:\Users\xxx\marvel-snap-bot\start.py", line 1, in <module>
    from utils import android_connection, global_utils
  File "C:\Users\xxx\marvel-snap-bot\utils\global_utils.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by paperc07** [comment]
ok well atleast its doing the adb I would check and go to cmd again and type in adb devices

**Comment by Krwawyy** [comment]
PS C:\Users\xxxx\\marvel-snap-bot> python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32

**Comment by Krwawyy** [comment]
Yup there is localhost:50459 device

**Comment by Krwawyy** [comment]
You are having similiar?

**Comment by paperc07** [comment]
no but who cares its working 

try 
pip3 install opencv-python

just for bs purposes and see what happens

**Comment by Krwawyy** [comment]
PS C:\Users\dawid\marvel-snap-bot> python start.py
Traceback (most recent call last):
  File "C:\Users\dawid\marvel-snap-bot\start.py", line 3, in <module>
    import info
  File "C:\Users\dawid\marvel-snap-bot\info.py", line 4, in <module>
    import hand_cards
  File "C:\Users\dawid\marvel-snap-bot\hand_cards.py", line 9, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'

**Comment by paperc07** [comment]
OK YESSSSSS!!!!

**Comment by paperc07** [comment]
I was here before just do 

pip install pyautogui 

and you should be good

**Comment by Krwawyy** [comment]
PS C:\Users\xxx\marvel-snap-bot> python start.py
Connection result: cannot connect to 127.0.0.1:5555: No connection could be made because the target machine actively refused it. (10061)

adb.exe: device '127.0.0.1:5555' not found
error: device '127.0.0.1:5555' not found
Traceback (most recent call last):
  File "C:\Users\xxx\marvel-snap-bot\start.py", line 23, in <module>
    screenshot_dimensions = screenshot.shape
                            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

😢

**Comment by paperc07** [comment]
god what is with your stuff actively refusing it and your firewall and stuff is turned off not even sure thats a fix

**Comment by Krwawyy** [comment]
Firewall and defender are off but its still looking for 127.0.0.1:5555 but it's acually 127.0.0.1:50459

**Comment by Krwawyy** [comment]
I got it i think

**Comment by Krwawyy** [comment]
Yes its working

**Comment by Krwawyy** [comment]
I've changed the ip everywhere in android_connection.py and global_utils.py to 127.0.0.1:50459 and now its working.
Thank you men for help, love ya ❤️

**Comment by paperc07** [comment]
Holy shit!!! Thank God

**Comment by paperc07** [comment]
so, just to wrap up, what can we say was the problem and how to fix it?

**Comment by Krwawyy** [comment]
Well there was a lot of problems, first one was the problem with the cv2, but not clue what helped, some of your fixes i guess. Second one was the problem with ip, in code there is port 5555 but mine was different so i had to change it in android_connection.py and global_utils.py.
And had to connect mannualy via "adb connect localhost:(port on bluestacks)"
