### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by paperc07** [AdriaGual/marvel-snap-bot#95]
@AdriaGual  Since new update its not clicking the play button it's clicking into the shop menu 

#33 I don't know if they changed anything doesn't look like it

**Comment by isaiahd1** [comment]
I think maybe they changed the resolution of the start menu. but for whatever reason the bot will click on the shop instead of the play button. In my experience as well.

**Comment by paperc07** [comment]
nvm I think I had to manually run the first one cause now its working

**Comment by paperc07** [comment]
ok yeah it only happens on startup, if you manually click start and then let it run it seems to work fine
